name: Auto Android APK Build

on:
  push:
    branches:
      - main # The pipeline runs whenever you push code to this branch

jobs:
  compile-and-build:
    name: Trigger EAS Cloud Build
    type: build
    params:
      platform: android
      profile: preview