name: Auto Android APK Build

on:
  push:
    branches:
      - main # The pipeline runs whenever you push code to this branch

jobs:
  compile-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗️ Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: npm

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🚀 Setup Expo EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_AUTO_BUILD_TOKEN }} # Reads your hidden secret key

      - name: ☁️ Trigger EAS Cloud Build
        run: eas build --platform android --profile preview --non-interactive